# Generated by Django 4.2.25 on 2025-11-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peca',
            old_name='codigo',
            new_name='codigo_sku',
        ),
    ]
