# Generated by Django 6.0 on 2025-12-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_codigo_peca_codigo_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peca',
            old_name='codigo_sku',
            new_name='codigo',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
